# Preload your files first
preload = /home/nolgra/Pictures/bg.png
preload = /home/nolgra/Pictures/bg.png

# Map them to the specific monitors found in your log
# DP-1 (Main) and HDMI-A-1 (Vertical)
wallpaper = DP-1, /home/nolgra/Pictures/bg.png
wallpaper = HDMI-A-1, /home/nolgra/Pictures/bg.png

# Optional: Disable the text at the bottom
splash = true

